-- tabe creation
create table
  public.users (
    id text not null,
    email text not null,
    phone text not null,
    full_name text not null,
    isAdmin boolean not null default false,
    created_at timestamp without time zone not null default current_timestamp,
    updated_at timestamp without time zone null,
    constraint users_pkey primary key (id)
  ) tablespace pg_default;

create unique index users_email_key on public.users using btree (email) tablespace pg_default;

create unique index users_phone_key on public.users using btree (phone) tablespace pg_default;

create table
  public.categories (
    id integer not null default nextval('categories_id_seq'::regclass),
    name text not null,
    image text not null,
    is_active boolean not null default true,
    created_at timestamp without time zone not null default current_timestamp,
    updated_at timestamp without time zone not null,
    constraint categories_pkey primary key (id)
  ) tablespace pg_default;

create index if not exists categories_name on public.categories using btree (name) tablespace pg_default;

create table
  public.products (
    id bigint generated by default as identity not null,
    name text not null,
    price double precision not null,
    profit double precision not null,
    image text not null,
    quantity integer not null default 0,
    is_active boolean not null default true,
    category_id integer not null,
    created_at timestamp without time zone not null default current_timestamp,
    updated_at timestamp without time zone not null,
    alert_threshold integer not null default 0,
    constraint products_pkey primary key (id),
    constraint products_category_id_fkey foreign key (category_id) references categories (id) on delete restrict
  ) tablespace pg_default;

create index if not exists products_name on public.products using btree (name) tablespace pg_default;

create table
  public.customers (
    id integer not null default nextval('customers_id_seq'::regclass),
    name text not null,
    phone text not null,
    address text null,
    created_at timestamp without time zone not null default current_timestamp,
    updated_at timestamp without time zone not null,
    constraint customers_pkey primary key (id)
  ) tablespace pg_default;

create index if not exists customers_name on public.customers using btree (name) tablespace pg_default;

-- seed 3 categories data ['Food', 'Drink', 'Dessert']
insert into public.categories (name, image, is_active, created_at, updated_at) values ('Food', 'food.jpeg', true, now(), now());
insert into public.categories (name, image, is_active, created_at, updated_at) values ('Drink', 'drink.jpg', true, now(), now());
insert into public.categories (name, image, is_active, created_at, updated_at) values ('Dessert', 'dessert.jpeg', true, now(), now());

-- seed 10 customers data
insert into public.customers (name, phone, address, created_at, updated_at) values ('Consommateur final', '0123456789', 'Address 1', now(), now());
insert into public.customers (name, phone, address, created_at, updated_at) values ('Customer 2', '0123456789', 'Address 2', '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.customers (name, phone, address, created_at, updated_at) values ('Customer 3', '0123456789', 'Address 3', '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.customers (name, phone, address, created_at, updated_at) values ('Customer 4', '0123456789', 'Address 4', '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.customers (name, phone, address, created_at, updated_at) values ('Customer 5', '0123456789', 'Address 5', '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.customers (name, phone, address, created_at, updated_at) values ('Customer 6', '0123456789', 'Address 6', '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.customers (name, phone, address, created_at, updated_at) values ('Customer 7', '0123456789', 'Address 7', '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.customers (name, phone, address, created_at, updated_at) values ('Customer 8', '0123456789', 'Address 8', '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.customers (name, phone, address, created_at, updated_at) values ('Customer 9', '0123456789', 'Address 9', '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.customers (name, phone, address, created_at, updated_at) values ( 'Customer 10', '0123456789', 'Address 10', '2023-08-16 00:00:00', '2023-08-16 00:00:00');

-- seed 10 products data with random category_id (1, 2, 3) and random dates
insert into public.products (name, price, profit, image, quantity, alert_threshold, is_active, category_id, created_at, updated_at) values ('Product 1', 100, 10, 'cook1.jpg', 10, 5, true, (floor(random() * 3) + 1), '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.products (name, price, profit, image, quantity, alert_threshold, is_active, category_id, created_at, updated_at) values ('Product 2', 200, 20, 'cook2.png', 10, 5, true, (floor(random() * 3) + 1), '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.products (name, price, profit, image, quantity, alert_threshold, is_active, category_id, created_at, updated_at) values ('Product 3', 300, 30, 'cook3.jpg', 10, 5, true, (floor(random() * 3) + 1), '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.products (name, price, profit, image, quantity, alert_threshold, is_active, category_id, created_at, updated_at) values ('Product 4', 400, 40, 'cook4.jpg', 10, 5, true, (floor(random() * 3) + 1), '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.products (name, price, profit, image, quantity, alert_threshold, is_active, category_id, created_at, updated_at) values ('Product 5', 500, 50, 'cook5.jpg', 10, 5, true, (floor(random() * 3) + 1), '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.products (name, price, profit, image, quantity, alert_threshold, is_active, category_id, created_at, updated_at) values ('Product 6', 600, 60, 'cook6.jpg', 10, 5, true, (floor(random() * 3) + 1), '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.products (name, price, profit, image, quantity, alert_threshold, is_active, category_id, created_at, updated_at) values ('Product 7', 700, 70, 'cook7.jpg', 10, 5, true, (floor(random() * 3) + 1), '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.products (name, price, profit, image, quantity, alert_threshold, is_active, category_id, created_at, updated_at) values ('Product 8', 800, 80, 'cook8.jpg', 10, 5, true, (floor(random() * 3) + 1), '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.products (name, price, profit, image, quantity, alert_threshold, is_active, category_id, created_at, updated_at) values ('Product 9', 900, 90, 'cook9.jpg', 10, 5, true, (floor(random() * 3) + 1), '2023-08-16 00:00:00', '2023-08-16 00:00:00');
insert into public.products (name, price, profit, image, quantity, alert_threshold, is_active, category_id, created_at, updated_at) values ( 'Product 10', 1000, 100, 'cook10.jpg', 10, 5, true, (floor(random() * 3) + 1), '2023-08-16 00:00:00', '2023-08-16 00:00:00');
