-- Table: public.products
create table
  public.products (
    id bigint generated by default as identity,
    name text not null,
    price double precision not null,
    profit double precision not null,
    image text not null,
    quantity integer not null default 0,
    alert_threshold integer not null default 0,
    is_active boolean not null default true,
    category_id integer not null,
    created_at timestamp without time zone not null default current_timestamp,
    updated_at timestamp without time zone not null,
    constraint products_pkey primary key (id),
    constraint products_category_id_fkey foreign key (category_id) references categories (id) on update cascade on delete restrict
  ) tablespace pg_default;

create index if not exists products_name on public.products using btree (name) tablespace pg_default;
comment on table public.products is 'Products';
comment on column public.products.id is 'The unique identifier of product';
comment on column public.products.name is 'The name of product';
comment on column public.products.price is 'Price of product';
comment on column public.products.profit is 'The profit made by selling product';
comment on column public.products.image is 'The image of product';
comment on column public.products.quantity is 'Available quantity of product';
comment on column public.products.is_active is 'The status of product';
comment on column public.products.category_id is 'The category related to product';
comment on column public.products.created_at is 'Date when product was created';
comment on column public.products.updated_at is 'Last date when product was updated';
