-- Table: public.coupons
create table
  public.coupons (
    id bigint generated by default as identity,
    code text not null,
    discount double precision not null,
    customer_id integer not null,
    is_active boolean not null default true,
    created_at timestamp without time zone not null default current_timestamp,
    updated_at timestamp without time zone not null,
    constraint coupons_pkey primary key (id),
    constraint coupons_customer_id_fkey foreign key (customer_id) references customers (id) on update cascade on delete restrict
  ) tablespace pg_default;
create unique index coupons_code_key on public.coupons using btree (code) tablespace pg_default;
create index if not exists coupons_code on public.coupons using btree (code) tablespace pg_default;
comment on table public.coupons is 'Coupons for customers';
comment on column public.coupons.id is 'The unique identifier of coupon';
comment on column public.coupons.code is 'The code of coupon';
comment on column public.coupons.discount is 'The amount of discount';
comment on column public.coupons.customer_id is 'The customer who owns the coupon';
comment on column public.coupons.is_active is 'The status of coupon';
comment on column public.coupons.created_at is 'Date when coupon was generated';
comment on column public.coupons.updated_at is 'Last date when coupon was updated';
