-- Table: public.orders
create table
  public.orders (
    id bigint generated by default as identity,
    name text not null,
    customer_id integer not null default 1,
    sub_total double precision not null,
    total_amount double precision not null,
    seller_id uuid not null,
    last_editor_id uuid not null,
    status public.order_status not null default 'pending',
    discount double precision not null default 0,
    coupon_code text null,
    note text null,
    created_at timestamp without time zone not null default current_timestamp,
    updated_at timestamp without time zone not null,
    constraint orders_pkey primary key (id),
    constraint orders_customer_id_fkey foreign key (customer_id) references customers (id) on update cascade on delete restrict,
    constraint orders_coupon_code_fkey foreign key (coupon_code) references coupons (code) on update cascade on delete set null,
    constraint orders_seller_id_fkey foreign key (seller_id) references users (id) on update cascade on delete restrict,
    constraint orders_last_editor_id_fkey foreign key (last_editor_id) references users (id) on update cascade on delete restrict
  ) tablespace pg_default;

create unique index orders_name_key on public.orders using btree (name) tablespace pg_default;
create unique index orders_coupon_code_key on public.orders using btree (coupon_code) tablespace pg_default;
create index if not exists orders_name_customer_id on public.orders using btree (name, customer_id) tablespace pg_default;

comment on table public.orders is 'Orders';
comment on column public.orders.id is 'The unique identifier of order';
comment on column public.orders.name is 'Order sequence like VT230902 means VT+currentYear+currentMonth+numberOfOrderInMonth';
comment on column public.orders.customer_id is 'The customer who made the order';
comment on column public.orders.sub_total is 'Sub total amount before discount';
comment on column public.orders.total_amount is 'Total amount paid by customer';
comment on column public.orders.seller_id is 'The seller who made the order';
comment on column public.orders.last_editor_id is 'Last editor id';
comment on column public.orders.status is 'The status of order (pending, paid, delivered, cancelled)';
comment on column public.orders.discount is 'Amount of discount';
comment on column public.orders.coupon_code is 'Coupon code used';
comment on column public.orders.note is 'Some note about order';
comment on column public.orders.created_at is 'Date when order was created';
comment on column public.orders.updated_at is 'Last date when order was updated';
