-- Table: public.order_items
create table
  public.order_items (
    id bigint generated by default as identity,
    order_id integer not null,
    product_id integer not null,
    quantity integer not null,
    price double precision not null,
    constraint order_items_pkey primary key (id),
    constraint order_items_order_id_fkey foreign key (order_id) references orders (id) on update cascade on delete cascade,
    constraint order_items_product_id_fkey foreign key (product_id) references products (id) on update cascade on delete cascade
  ) tablespace pg_default;

create unique index order_items_order_id_product_id_key on public.order_items using btree (order_id, product_id) tablespace pg_default;
comment on table public.order_items is 'Order items';
comment on column public.order_items.id is 'The unique identifier of order item';
comment on column public.order_items.order_id is 'The order related to order item';
comment on column public.order_items.product_id is 'The product related to order item';
comment on column public.order_items.quantity is 'Quantity of product added to order';
comment on column public.order_items.price is 'Price of product at the time of order';
